### ISSUE TITLE
AL Register MOD

### ISSUE THREAD

**Issue by douweyntema** [AnnetLab/AL-PHP-Fusion-Addons#1]
PHP error output is enabled bij default I Think, see this line in error_handling_include.php:

error_reporting(E_ALL ^ E_STRICT);

I added line in maincore:
error_reporting(E_ALL) but things did not change. Seems like the Javascript functions are not working.

**Comment by hotrush** [comment]
You need to enable 2 php directives in your php.ini
display_errors = On
display_startup_errors = On

**Comment by douweyntema** [comment]
I Modified the php directives and restarted Apache. 
Stil the same issue
Again: I Think the problem is in the Javascript. I did some debugging bij enabling some alerts in it.

**Comment by hotrush** [comment]
http://joxi.ru/GrqgVlyIOejP2z here your error.
try to exec next if you use linux
`sudo apt-get install php5-json`

**Comment by douweyntema** [comment]
Ok, I Am running PHP 5.1 so there is no Json support availble.
Thanks for your help.
BTW: What debugging tool are you using?

**Comment by hotrush** [comment]
Oh, 5.1 has been released in 2006. You need to upgrade your server :)
This is google chrome developer tool.

**Comment by douweyntema** [comment]
Yeah You are right.
I Upgraded my server to php5.3 and the mod is working.
Except after the last step this error appears:

To use reCAPTCHA you must get an API key from https://www.google.com/recaptcha/admin/create

I have NOT enabled recapcha on my site but secureimage2.

**Comment by hotrush** [comment]
Do not remember about recaptcha, anyway recaptcha better than secureimage2)
